volumes:
  postgres_data: {}
  redis_data: {}

services:
  db:
    image: "postgres:16"
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - stack.env
    environment:
      - TZ=Europe/Moscow
    ports:
      - 5432:5432
  redis:
    image: "redis:7.2.5-alpine"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      - TZ=Europe/Moscow
  api:
    image: ghcr.io/egortarasov/t1/api:dev
    build:
      context: backend/.
      dockerfile: Dockerfile
    restart: always
    command: fastapi run src/main.py
    ports:
      - 8080:8000
    depends_on:
      - db
      - redis
    env_file:
      - stack.env
    environment:
      - TZ=Europe/Moscow
      - DOCKER_MODE=True
  ui:
    image: ghcr.io/egortarasov/t1/ui@sha256:693b17b86a530a82c6a18a022cc3d68b0e8c8c091194f86c665d2896ca883ba2
    build:
      context: frontend/.
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    env_file:
      - stack.env
    environment:
      - TZ=Europe/Moscow
