volumes:
  postgres_data: {}
  redis_data: {}

services:
  db:
    image: "postgres:16"
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - stack.env
    environment:
      - TZ=Europe/Moscow
    ports:
      - 5432:5432
  redis:
    image: "redis:7.2.5-alpine"
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    environment:
      - TZ=Europe/Moscow
  api:
    image: ghrc.io/egortarasov/t1/api:dev
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: fastapi run src/main.py
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - stack.env
    environment:
      - TZ=Europe/Moscow
      - DOCKER_MODE=True
