"""updated_vacancy_model

Revision ID: 186a037ca7da
Revises: 16a694a493f5
Create Date: 2024-10-01 21:38:34.366592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '186a037ca7da'
down_revision: Union[str, None] = '16a694a493f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancys', sa.Column('key_skills', postgresql.ARRAY(sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancys', 'key_skills')
    # ### end Alembic commands ###
