"""Added salary

Revision ID: 44bcf4317986
Revises: 8a728645b7b9
Create Date: 2024-10-06 11:15:08.909598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44bcf4317986'
down_revision: Union[str, None] = '8a728645b7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('salary_high', sa.Integer(), nullable=False))
    op.add_column('vacancies', sa.Column('salary_low', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'salary_low')
    op.drop_column('vacancies', 'salary_high')
    # ### end Alembic commands ###
