"""vacancy_fields

Revision ID: 95fa9e9624d5
Revises: 9c06dfabe431
Create Date: 2024-10-06 14:38:25.510385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95fa9e9624d5'
down_revision: Union[str, None] = '9c06dfabe431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('first_name', sa.Text(), nullable=False))
    op.add_column('candidates', sa.Column('last_name', sa.Text(), nullable=False))
    op.add_column('candidates', sa.Column('city', sa.Text(), nullable=False))
    op.add_column('candidates', sa.Column('country', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'country')
    op.drop_column('candidates', 'city')
    op.drop_column('candidates', 'last_name')
    op.drop_column('candidates', 'first_name')
    # ### end Alembic commands ###
