"""candidate_changes

Revision ID: 9c06dfabe431
Revises: f4bc1e54902e
Create Date: 2024-10-06 13:43:24.722365

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9c06dfabe431"
down_revision: Union[str, None] = "f4bc1e54902e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE candidates ALTER COLUMN education TYPE JSON USING education::json"
    )
    op.execute(
        "ALTER TABLE candidates ALTER COLUMN experience TYPE JSON USING experience::json"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "candidates",
        "experience",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "candidates",
        "education",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
