"""vacancy_salary

Revision ID: f4bc1e54902e
Revises: 8a728645b7b9
Create Date: 2024-10-06 12:19:28.876405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bc1e54902e'
down_revision: Union[str, None] = '8a728645b7b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('salary_high', sa.Integer(), server_default='30000', nullable=False))
    op.add_column('vacancies', sa.Column('salary_low', sa.Integer(), server_default='70000', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'salary_low')
    op.drop_column('vacancies', 'salary_high')
    # ### end Alembic commands ###
